@ECHO OFF

IF %PROCESSOR_ARCHITECTURE%==x86 (
  SET APP_ROOT=%ADPROOT%\examples_perseus6010\perseus6010_mo1000_mi125_bsdk\host\prj_win\Release
) ELSE ( 
  SET APP_ROOT=%ADPROOT%\examples_perseus6010\perseus6010_mo1000_mi125_bsdk\host\prj_win\x64\Release
)

::Application parameters
SET IP_ADDR_PERSEUS=192.168.0.101

::Optional parameters
:: TEST_MODE=0  => DDS
:: TEST_MODE=1  => Pass-Through

:: CONFIGURATION_MODE=0 => ALL
:: CONFIGURATION_MODE=1 => BOT ONLY
:: CONFIGURATION_MODE=2 => TOP ONLY
:: CONFIGURATION_MODE=3 => DDS ONLY
:: CONFIGURATION_MODE=4 => PASS-THROUGH ONLY
SET TEST_MODE=1
SET CONFIGURATION_MODE=0

::MO1000 Bottom parameters
SET BOTTOM_CLOCK_SOURCE=1
SET BOTTOM_CLOCK_FREQUENCY=125000000
SET BOTTOM_DAC_CLOCK_FREQUENCY=250000000
SET BOTTOM_MASTER_CLOCK_FREQUENCY=125000000
SET BOTTOM_INTERPOLATION=0
SET BOTTOM_ACTIVE_CHANNELS=3
SET BOTTOM_MO1000_PARAM=%BOTTOM_CLOCK_SOURCE% %BOTTOM_CLOCK_FREQUENCY% %BOTTOM_DAC_CLOCK_FREQUENCY% %BOTTOM_MASTER_CLOCK_FREQUENCY% %BOTTOM_INTERPOLATION% %BOTTOM_ACTIVE_CHANNELS%

::MI125 Top parameters
SET TOP_CHANNEL_USED=0

REM %APP_ROOT%\perseus6010_mo1000_mi125.exe %IP_ADDR_PERSEUS% %TEST_MODE% %CONFIGURATION_MODE% %BOTTOM_MO1000_PARAM% %TOP_CHANNEL_USED%
%APP_ROOT%\perseus6010_mo1000_mi125.exe %IP_ADDR_PERSEUS%